var animdefs = {
   // "anim_pulse":"pulse 1s linear 0s infinite normal forwards",
    "anim_placeItem": "placeTray 1s 0s 1 linear normal forwards",
    "anim_tube4ToBath": "tube4ToBath 1s linear 0s 1 normal forwards",
    "anim_tube1ToBath": "tube1ToBath 1s linear 0s 1 normal forwards",
    "anim_insertRack": "insertRack 1.8s linear 0s 1 normal forwards",
    "anim_moveTip4": "moveTip4 5s linear 0s 1 normal forwards",
    "anim_toTopView2": "toTopView2 1s 0s 1 linear normal forwards",
    "anim_moveLoadingDye2": "moveLoadingDye2 2s linear 0s 1 normal forwards",
    "anim_tipToBin": "tipToBin .5s linear 0s 1 normal forwards",
    "anim_tipReset": "tipReset .1s linear 0s 1 normal forwards",
    "anim_moveBlock": "moveBlock 1s linear 0s 1 normal forwards",
    "anim_flickTube": "flickTube 0.6s linear 0s 1 normal forwards",
    "anim_pipetteFromBinToPrep": "pipetteFromBinToPrep 1.6s linear 0s 1 normal forwards",
    "anim_quickFadeIn": "quickFadeIn .125s 0s 1 linear normal forwards",
    "anim_quickFadeOut": "quickFadeOut .125s 0s 1 linear normal forwards",
    "anim_slowFadeIn": "slowFadeIn 2s 0s 1 linear normal forwards",
    "anim_slowFadeOut": "slowFadeOut 2s 0s 1 linear normal forwards",
    "anim_tipHidden": "tipHidden 0.1s linear 0s normal forwards",
    "anim_tipVisible": "tipVisible 0.1s linear 0s normal forwards",
    "anim_pressTube3": "pressTube3 0.3s linear 0s 1 normal forwards",
    "anim_hideTip1": "hideTip1 .7s linear 0s 1 normal forwards",
    "anim_hideTipp1": "hideTipp1 .9s linear 0s 1 normal forwards",
    "anim_tube2ToBath": "tube2ToBath 1s linear 0s 1 normal forwards",
    "anim_closeCap": "closeCap 0.5s linear normal forwards",
    "anim_moveTube": "moveTube 0.5s linear 0s 1 normal forwards",
    "anim_pipetteToBin": "pipetteToBin 1.6s linear 0s 1 normal forwards",
    "anim_pipetteToTube": "pipetteToTube 3.4s linear 0s 1 normal forwards",
    "anim_mixTubeContent": "mixTubeContent .9s linear 0s 5 normal forwards",
    "anim_mixs0TubeBody": "mixs0TubeBody .9s linear 0s 5 normal forwards",
    "anim_returnLoadingDye1": "returnLoadingDye1 2s linear 0s 1 normal forwards",
    "anim_moveLoadingDye": "moveLoadingDye 2s linear 0s 1 normal forwards",
    "anim_moveLoadingDyeback": "moveLoadingDyeback 2s linear 0s 1 normal forwards",
    "anim_moveEnz": "moveEnz 0.5s linear 0s 1 normal forwards",
    "anim_moveEnzBack": "moveEnzBack 1.5s linear 0s 1 normal forwards",
    "anim_removeComb": "removeComb 1s 0s 1 linear normal forwards",
    "anim_replaceLid": "replaceLid 0.9s linear 0s 1 normal forwards",
    "anim_pourStain": "pourStain 2s 0s 1 linear normal forwards",
    "anim_pourStainRev": "pourStainRev 2s 0s 1 linear normal forwards",
    "anim_rotateCap": "rotateCap 0.5s linear forwards",
    "anim_lowerTip1": "lowerTip1 0.4s linear 0s 1 normal forwards",
    "anim_insertTube0": "insertTube0 1.8s linear 0s 1 normal forwards",
    "anim_insertTube1": "insertTube1 1.8s linear 0s 1 normal forwards",
    "anim_insertTube2": "insertTube2 1.8s linear 0s 1 normal forwards",
    "anim_insertTube3": "insertTube3 1.8s linear 0s 1 normal forwards",
    "anim_insertTube4": "insertTube4 1.8s linear 0s 1 normal forwards",
    "anim_insertTube5": "insertTube5 1.8s linear 0s 1 normal forwards",
    "anim_addTip1": "addTip1 3s linear 0s 1 normal forwards",
    "anim_PrepPipette": "PrepPipette 1s linear 0s 1 normal forwards",
    "anim_pipetteBacktoNormal": "pipetteBacktoNormal 2s linear 0s 1 normal forwards",
    "anim_addTipp1": "addTipp1 3s linear 0s 1 normal forwards",
    "anim_addDyeToTube": "addDyeToTube 3s linear 0s 1 normal forwards",
    "anim_tubeDown": "tubeDown 0.5s linear 0s 1 normal forwards",
    "anim_tipToTube4": "tipToTube4 3.4s linear 0s 1 normal forwards",
    "anim_removeLid": "removeLid 0.9s linear 0s 1 normal forwards",
    "anim_pressTube0": "pressTube0 0.3s linear 0s 1 normal forwards",
    "anim_pressTube1": "pressTube1 0.3s linear 0s 1 normal forwards",
    "anim_pressTube2": "pressTube2 0.3s linear 0s 1 normal forwards",
    "anim_tube3ToBath": "tube3ToBath 1s linear 0s 1 normal forwards",
    "anim_pressTube4": "pressTube4 0.3s linear 0s 1 normal forwards",
    "anim_moveTip3": "moveTip3 5s linear 0s 1 normal forwards",
    "anim_pressTube5": "pressTube5 0.3s linear 0s 1 normal forwards",
    "anim_tube0ToBath": "tube0ToBath 1s linear 0s 1 normal forwards",
    "anim_tapTube": "tapTube 1.6s linear 0s 1 normal forwards",
    "anim_tipToTube1": "tipToTube1 3.4s linear 0s 1 normal forwards",

    "anim_movePipette": "movePipette 8s linear 0s 1 normal forwards",
    "anim_ejectTip": "ejectTip 0.8s linear 0s 1 normal forwards",
    "anim_lowerPipette": "lowerPipette 0.4s linear 0s normal forwards",
    "anim_tube5ToBath": "tube5ToBath 1s linear 0s 1 normal forwards",
    "anim_moveTip1": "moveTip1 5s linear 0s 1 normal forwards",
    "anim_mooveTip": "mooveTip 5s linear 0s 1 normal forwards",

    "anim_addTip4": "addTip4 5s linear 0s 1 normal forwards",
    "anim_moveTip2": "moveTip2 5s linear 0s 1 normal forwards",
    "anim_addTip2": "addTip2 5s linear 0s 1 normal forwards",
    "anim_addTip3": "addTip3 5s linear 0s 1 normal forwards"
}
